### ISSUE TITLE
有iOS版本的吗

### ISSUE THREAD

**Issue by eric1202** [kareluo/Imaging#15]
github似乎并没有检索相关的代码库, 希望能提供帮助

**Comment by fairytale110** [comment]
https://github.com/lincf0912/LFMediaEditingController

这个有 OC版，我觉得还不错

**Comment by eric1202** [comment]
thanks!

在 2019-04-16 14:27:04，"fairytale110" <notifications@github.com> 写道：


https://github.com/lincf0912/LFMediaEditingController

这个有 OC版，我觉得还不错

**Comment by kareluo** [comment]
没有iOS版本
